### ISSUE TITLE
Crazy Vouchers Item Name Bug

### ISSUE THREAD

**Issue by DecypherMC** [Crazy-Crew/CrazyVouchers#25]
### Server Version

1.19.3

### Server Platform

Paper

### Describe the bug

One of my vouchers for a tag is removing the name when it's moved in an inventory. I put the video and a link to my config in "steps to reproduce". Also, I'm using a custom paper fork of 1.19 not 1.19.3 but it doesn't give me that option. I'm using version 2.9.14.2 of the plugin

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by RyderBelserion** [comment]
Try it on a normal paper server first
