### ISSUE TITLE
Player Heads on 1.21.4

### ISSUE THREAD

**Issue by PanHaskins** [Crazy-Crew/CrazyVouchers#80]
### Plugin Version

4.0.0

### Server Version

1.21.1

### Server Platform

Paper

### Describe the bug

Heads don't work. After getting the voucher I have in my hand a classic player head without texture.

Format playerhead -> player: 'http://textures.minecraft.net/texture/758cd2451f6f600f3eafb3c46ab8d005137de1657ab197afb46d741d5f950bb6'
I tried with https too.

### Steps to reproduce

1. Turn on your server with 1.21.4 paper.
2. Add CrazyVouchers
3. Create or give vouchers with playerhead texture (player head from https://minecraft-heads.com/)

### Additional context

Add back support for base64 heads. Other plugins have it. Why not there...

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
Not a bug, check discord.
